# This workflow should be placed in your CV repository (.github/workflows/trigger-profile-update.yml)
# Repository: ja754969.github.io

name: Trigger Profile Update

on:
  push:
    branches: [main, master]
    paths:
      - 'index.html'
      - 'cv/**'
      - '_data/**'
      - '_config.yml'
  
  workflow_dispatch:

jobs:
  trigger-profile-update:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger profile repository update
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PROFILE_UPDATE_TOKEN }}" \
          https://api.github.com/repos/ja754969/ja754969/dispatches \
          -d '{"event_type":"cv-updated","client_payload":{"updated_at":"'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"}}'

    - name: Log trigger
      run: |
        echo "Profile update triggered at $(date)"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
